#!/bin/bash
# Designed to be run from the crontab, for example:
# To log every 5 mins your laptop's temperature to your $SG_HOST
# */5 * * * * ID=temp sg-client -d $SG_HOST -g temp /sys/class/thermal/thermal_zone0/temp

sr=/var/sg # sg's root

# to identify where the data is coming from
id=$(hostname)

# Every graph needs a name
g="unnamed"

sent=false

while getopts "r:g:d:i:" o
do
	case "$o" in
	(g) g="$OPTARG";; # graph name
	(d) d="$OPTARG";; # destination hostname
	(r) dr="$OPTARG";; # destination root directory
	(i) id="$OPTARG";;# override hostname as client id
	esac
done
shift $((OPTIND - 1))

# Crucial hierachy e.g. /var/sg/machine-id/temperature/022.csv, 022 is the day of the year
f="$sr/$id/$g/$(date +%j).csv"

# MUST be rooted by EPOCH time
if test -f "$1"
then
	m="$(date +%s) $(< $1)"
else
	m="$(date +%s) $(< /dev/stdin)"
fi

mkdir -p $(dirname $f)
echo $m >> $f
test "$?" -eq 0 &&

if test "$d"
then
	flock -n "/tmp/sg-${id}-${g}" -c "rsync --append -r $sr/$id/$g/ $d:${dr:-$sr}/$id/$g/"
fi
