#!/bin/bash
# Designed to be run from the crontab, for example:
# To log every 5 mins your laptop's temperature to your $SG_HOST
# */5 * * * * ID=temp sg-client -d $SG_HOST -g temp /sys/class/thermal/thermal_zone0/temp

# Check if time is sane
if test $(date +%s) -lt 1378882344
then
	echo "Time is in the past: $(date)" 1>&2
	exit 1
fi

# Setup your SSH_ENV like so: https://github.com/kaihendry/Kai-s--HOME/blob/master/.xinitrc
SSH_ENV=$HOME/.ssh/environment
test -e "$SSH_ENV" && . $SSH_ENV

sr=/var/sg # sg's root

# to identify where the data is coming from
id=$(hostname)

# Every graph needs a name
g="unnamed"

while getopts "r:g:d:i:" o
do
	case "$o" in
	(g) g="$OPTARG" ;; # graph name
	(d) d="$OPTARG" ;; # destination hostname
	(r) dr="$OPTARG";; # destination root directory
	(i) id="$OPTARG";; # override hostname as client id
	esac
done
shift $((OPTIND - 1))

# Crucial hierachy e.g. /var/sg/machine-id/temperature/14022.csv, 022 is the day of the year, 14 is last two digits of the year
f="$sr/$id/$g/$(date -u +%y%j).csv"

# MUST be rooted by EPOCH time
if test -f "$1"
then
	m="$(date +%s) $(< $1)"
else
	m="$(date +%s) $(< /dev/stdin)"
fi

mkdir -p "$(dirname "$f")"
echo $m >> "$f" || exit

if test "$d"
then
	# Directing stderr to remove annoying Could not chdir to home directory /home/stats: No such file or directory
	# Where rsync tries to chdir to /home/stats, stat's $HOME, despite the Match user stats's ChrootDirectory /var/sg setting
	flock -n "/tmp/sg-${id}-${g}" -c "rsync -e ssh --append -r $sr/$id/$g/*.csv $d:${dr:-$sr}/$id/$g/" 2>/dev/null
fi
