#!/bin/bash

cache=${XDG_CACHE_HOME:-$HOME/.cache}/sg

np="$(mktemp -d)/sg-$$"
mkfifo "$np" || exit

inotifywait -r -m -e CLOSE_WRITE "$cache" > "$np" & ipid=$!

trap "kill $ipid; rm -f $np" EXIT

while read -r dir event filename
do
	# If it's not a CSV file changing, then we ignore the event
	if test "${filename##*.}" != "csv"; then continue; fi

	cd "$dir"

	# Generate the graph
	for i in *.sh
	do
		if test "$DEBUG"
		then
			echo $(date +%s): ${dir}${i}
			sh -x "$i"
		else
			sh "$i"
		fi
	done

done < "$np"
