#!/bin/bash

export WWWDIR=${WWWDIR:-/var/www}
cache=${XDG_CACHE_HOME:-$HOME/.cache}/sg

np="$(mktemp -d)/sg-$$"
mkfifo "$np" || exit

inotifywait -r -m -e CLOSE_WRITE "$cache" > "$np" & ipid=$!

trap "kill $ipid; rm -f $np" EXIT

while read -r dir event filename
do
	if test "${filename##*.}" != "csv"; then continue; fi
	cd "$dir"
	for i in *.sh
	do
		sh "$i"
		test "$DEBUG" && echo $(date +%s): ${dir}${i}
	done
done < "$np"
